// <auto-generated />
namespace CRUD_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Alumnos02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alumnos02));
        
        string IMigrationMetadata.Id
        {
            get { return "202201242328054_Alumnos-02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
